package com.example.sqlide.DataScience.Model;

public enum Models {

    LINEAR_REGRESSION,
    RANDOM_FOREST_REGRESSION,
    GRADIENT_REGRESSION,
    TREE_REGRESSION,
    LOGISTIC_REGRESSION,
    LOGISTIC_BINOMIAL_REGRESSION,
    LOGISTIC_MULTIMODAL_REGRESSION,
    KNN,

    RANDOM_FOREST_CLASSIFICATION,
    GRADIENT_CLASSIFICATION,




}
