package com.example.sqlide.Container.Editor.Words;

public abstract class SQLWords {
    
    private static final String[][] words = {
            // SQLite
            {
            // word keys
            "ABORT", "ACTION", "ADD", "AFTER", "ALL", "ALTER", "ALWAYS", "ANALYZE", "AND", "AS", "ASC", "ATTACH", "AUTOINCREMENT",
            "BEFORE", "BEGIN", "BETWEEN", "BY", "CASCADE", "CASE", "CAST", "CHECK", "COLLATE", "COLUMN", "COMMIT", "CONFLICT",
            "CONSTRAINT", "CREATE", "CROSS", "CURRENT", "CURRENT_DATE", "CURRENT_TIME", "CURRENT_TIMESTAMP", "DATABASE", "DEFAULT",
            "DEFERRABLE", "DEFERRED", "DELETE", "DESC", "DETACH", "DISTINCT", "DO", "DROP", "EACH", "ELSE", "END", "ESCAPE",
            "EXCEPT", "EXCLUDE", "EXCLUSIVE", "EXISTS", "EXPLAIN", "FAIL", "FILTER", "FIRST", "FOLLOWING", "FOR", "FOREIGN",
            "FROM", "FULL", "GENERATED", "GLOB", "GROUP", "GROUPS", "HAVING", "IF", "IGNORE", "IMMEDIATE", "IN", "INDEX",
            "INDEXED", "INITIALLY", "INNER", "INSERT", "INSTEAD", "INTERSECT", "INTO", "IS", "ISNULL", "JOIN", "KEY", "LAST",
            "LEFT", "LIKE", "LIMIT", "MATCH", "MATERIALIZED", "NATURAL", "NO", "NOT", "NOTHING", "NOTNULL", "NULL", "NULLS",
            "OF", "OFFSET", "ON", "OR", "ORDER", "OTHERS", "OUTER", "OVER", "PARTITION", "PLAN", "PRAGMA", "PRECEDING",
            "PRIMARY", "QUERY", "RAISE", "RANGE", "RECURSIVE", "REFERENCES", "REGEXP", "REINDEX", "RELEASE", "RENAME",
            "REPLACE", "RESTRICT", "RETURNING", "RIGHT", "ROLLBACK", "ROW", "ROWS", "SAVEPOINT", "SELECT", "SET", "TABLE",
            "TEMP", "TEMPORARY", "THEN", "TIES", "TO", "TRANSACTION", "TRIGGER", "UNBOUNDED", "UNION", "UNIQUE", "UPDATE",
            "USING", "VACUUM", "VALUES", "VIEW", "VIRTUAL", "WHEN", "WHERE", "WINDOW", "WITH", "WITHOUT",
            // types
            "INT", "INTEGER", "TINYINT", "SMALLINT", "MEDIUMINT", "BIGINT", "UNSIGNED BIG INT", "INT2", "INT8", "CHARACTER",
            "VARCHAR", "VARYING CHARACTER", "NCHAR", "NATIVE CHARACTER", "NVARCHAR", "TEXT", "CLOB", "BLOB", "REAL", "DOUBLE",
            "DOUBLE PRECISION", "FLOAT", "NUMERIC", "DECIMAL", "BOOLEAN", "DATE", "DATETIME",
            // function keys
            "AVG()", "COUNT()", "GROUP_CONCAT()", "MAX()", "MIN()", "SUM()", "TOTAL()", "CHAR()", "INSTR()", "LENGTH()",
            "LOWER()", "LTRIM()", "QUOTE()", "REPLACE()", "RTRIM()", "SUBSTR()", "SUBSTRING()", "TRIM()", "UPPER()",
            "Function", "ABS()", "ACOS()", "ACOSH()", "ASIN()", "ASINH()", "ATAN()", "ATANH()", "ATAN2()", "CEIL()",
            "CEILING()", "COS()", "COSH()", "DEGREES()", "EXP()", "FLOOR()", "LN()", "LOG()", "LOG10()", "LOG2()",
            "MAX()", "MIN()", "MOD()", "PI()", "POW()", "POWER()", "RADIANS()", "RANDOM()", "ROUND()", "SIGN()", "SIN()",
            "SINH()", "SQRT()", "TAN()", "TANH()", "TRUNC()", "DATE()", "DATETIME()", "JULIANDAY()", "NOW()", "STRFTIME()",
            "TIME()", "UNIXEPOCH()", "CASE()", "CHANGES()", "COALESCE()", "FORMAT()", "GLOB()", "HEX()", "IFNULL()", "IIF()",
            "LAST_INSERT_ROWID()", "LIKE()", "NULLIF()", "PRINTF()", "RANDOMBLOB()", "SOUNDEX()", "SQLITE_SOURCE_ID()",
            "SQLITE_VERSION()", "TOTAL_CHANGES()", "TYPEOF()", "UNICODE()", "ZEROBLOB()"},
            // MySQL
            {
                    "ACCESSIBLE", "ACCOUNT", "ACTION", "ACTIVE", "ADD", "ADMIN", "AFTER", "AGAINST", "AGGREGATE", "ALGORITHM",
                    "ALL", "ALTER", "ALWAYS", "ANALYZE", "AND", "ANY", "ARRAY", "AS", "ASC", "ASCII", "ASENSITIVE",
                    "AT", "ATTRIBUTE", "AUTHENTICATION", "AUTO", "AUTOEXTEND_SIZE", "AUTO_INCREMENT", "AVG", "AVG_ROW_LENGTH",
                    "B", "BACKUP", "BEFORE", "BEGIN", "BERNOULLI", "BETWEEN", "BIGINT", "BINARY", "BINLOG", "BIT",
                    "BLOB", "BLOCK", "BOOL", "BOOLEAN", "BOTH", "BTREE", "BUCKETS", "BULK", "BY", "BYTE", "C",
                    "CACHE", "CALL", "CASCADE", "CASCADED", "CASE", "CATALOG_NAME", "CHAIN", "CHALLENGE_RESPONSE", "CHANGE",
                    "CHANGED", "CHANNEL", "CHAR", "CHARACTER", "CHARSET", "CHECK", "CHECKSUM", "CIPHER", "CLASS_ORIGIN",
                    "CLIENT", "CLONE", "CLOSE", "COALESCE", "CODE", "COLLATE", "COLLATION", "COLUMN", "COLUMNS", "COLUMN_FORMAT",
                    "COLUMN_NAME", "COMMENT", "COMMIT", "COMMITTED", "COMPACT", "COMPLETION", "COMPONENT", "COMPRESSED", "COMPRESSION",
                    "CONCURRENT", "CONDITION", "CONNECTION", "CONSISTENT", "CONSTRAINT", "CONSTRAINT_CATALOG", "CONSTRAINT_NAME",
                    "CONSTRAINT_SCHEMA", "CONTAINS", "CONTEXT", "CONTINUE", "CONVERT", "CPU", "CREATE", "CROSS", "CUBE", "CUME_DIST",
                    "CURRENT", "CURRENT_DATE", "CURRENT_TIME", "CURRENT_TIMESTAMP", "CURRENT_USER", "CURSOR", "CURSOR_NAME", "D",
                    "DATA", "DATABASE", "DATABASES", "DATAFILE", "DATE", "DATETIME", "DAY", "DAY_HOUR", "DAY_MICROSECOND",
                    "DAY_MINUTE", "DAY_SECOND", "DEALLOCATE", "DEC", "DECIMAL", "DECLARE", "DEFAULT", "DEFAULT_AUTH", "DEFINER",
                    "DEFINITION", "DELAYED", "DELAY_KEY_WRITE", "DELETE", "DENSE_RANK", "DESC", "DESCRIBE", "DESCRIPTION", "DETERMINISTIC",
                    "DIAGNOSTICS", "DIRECTORY", "DISABLE", "DISCARD", "DISK", "DISTINCT", "DISTINCTROW", "DIV", "DO", "DOUBLE",
                    "DROP", "DUAL", "DUMPFILE", "DUPLICATE", "DYNAMIC", "E", "EACH", "ELSE", "ELSEIF", "EMPTY",
                    "ENABLE", "ENCLOSED", "ENCRYPTION", "END", "ENDS", "ENFORCED", "ENGINE", "ENGINES", "ENGINE_ATTRIBUTE", "ENUM",
                    "ERROR", "ERRORS", "ESCAPE", "ESCAPED", "EVENT", "EVENTS", "EVERY", "EXCEPT", "EXCHANGE",
                    "EXCLUDE", "EXECUTE", "EXISTS", "EXIT", "EXPANSION", "EXPIRE", "EXPLAIN", "EXPORT", "EXTENDED", "EXTENT_SIZE",
                    "F", "FACTOR", "FAILED_LOGIN_ATTEMPTS", "FALSE", "FAST", "FAULTS", "FETCH", "FIELDS", "FILE", "FILE_BLOCK_SIZE",
                    "FILTER", "FINISH", "FIRST", "FIRST_VALUE", "FIXED", "FLOAT", "FLOAT4", "FLOAT8", "FLUSH", "FOLLOWING",
                    "FOLLOWS", "FOR", "FORCE", "FOREIGN", "FORMAT", "FOUND", "FROM", "FULL", "FULLTEXT", "FUNCTION",
                    "G", "GENERAL", "GENERATE", "GENERATED", "GEOMCOLLECTION", "GEOMETRY", "GEOMETRYCOLLECTION", "GET", "GET_FORMAT",
                    "GET_SOURCE_PUBLIC_KEY", "GLOBAL", "GRANT", "GRANTS", "GROUP", "GROUPING", "GROUPS", "GROUP_REPLICATION", "GTIDS",
                    "GTID_ONLY", "H", "HANDLER", "HASH", "HAVING", "HEADER", "HELP", "HIGH_PRIORITY", "HISTOGRAM", "HISTORY",
                    "HOST", "HOSTS", "HOUR", "HOUR_MICROSECOND", "HOUR_MINUTE", "HOUR_SECOND", "I", "IDENTIFIED", "IF",
                    "IGNORE", "IGNORE_SERVER_IDS", "IMPORT", "IN", "INACTIVE", "INDEX", "INDEXES", "INFILE", "INITIAL",
                    "INITIAL_SIZE", "INITIATE", "INNER", "INOUT", "INSENSITIVE", "INSERT", "INSERT_METHOD", "INSTALL", "INSTANCE",
                    "INT", "INT1", "INT2", "INT3", "INT4", "INT8", "INTEGER", "INTERSECT", "INTERVAL", "INTO", "INVISIBLE",
                    "INVOKER", "IO", "IO_AFTER_GTIDS", "IO_BEFORE_GTIDS", "IO_THREAD", "IPC", "IS", "ISOLATION", "ISSUER",
                    "ITERATE", "J", "JOIN", "JSON", "JSON_TABLE", "JSON_VALUE", "K", "KEY", "KEYRING", "KEYS", "KEY_BLOCK_SIZE",
                    "KILL", "L", "LAG", "LANGUAGE", "LAST", "LAST_VALUE", "LATERAL", "LEAD", "LEADING", "LEAVE",
                    "LEAVES", "LEFT", "LESS", "LEVEL", "LIBRARY", "LIKE", "LIMIT", "LINEAR", "LINES", "LINESTRING",
                    "LIST", "LOAD", "LOCAL", "LOCALTIME", "LOCALTIMESTAMP", "LOCK", "LOCKED", "LOCKS", "LOG", "LOGFILE",
                    "LOGS", "LONG", "LONGBLOB", "LONGTEXT", "LOOP", "LOW_PRIORITY", "M", "MANUAL", "MASTER", "MATCH",
                    "MAXVALUE", "MAX_CONNECTIONS_PER_HOUR", "MAX_QUERIES_PER_HOUR", "MAX_ROWS", "MAX_SIZE", "MAX_UPDATES_PER_HOUR",
                    "MAX_USER_CONNECTIONS", "MEDIUM", "MEDIUMBLOB", "MEDIUMINT", "MEDIUMTEXT", "MEMBER", "MEMORY", "MERGE",
                    "MESSAGE_TEXT", "MICROSECOND", "MIDDLEINT", "MIGRATE", "MINUTE", "MINUTE_MICROSECOND", "MINUTE_SECOND",
                    "MIN_ROWS", "MOD", "MODE", "MODIFIES", "MODIFY", "MONTH", "MULTILINESTRING", "MULTIPOINT", "MULTIPOLYGON",
                    "MUTEX", "MYSQL_ERRNO", "N", "NAME", "NAMES", "NATIONAL", "NATURAL", "NCHAR", "NDB", "NDBCLUSTER",
                    "NESTED", "NETWORK_NAMESPACE", "NEVER", "NEW", "NEXT", "NO", "NODEGROUP", "NONE", "NOT", "NOWAIT",
                    "NO_WAIT", "NO_WRITE_TO_BINLOG", "NTH_VALUE", "NTILE", "NULL", "NULLS", "NUMBER", "NUMERIC", "NVARCHAR",
                    "O", "OF", "OFF", "OFFSET", "OJ", "OLD", "ON", "ONE", "ONLY", "OPEN", "OPTIMIZE", "OPTIMIZER_COSTS",
                    "OPTION", "OPTIONAL", "OPTIONALLY", "OPTIONS", "OR", "ORDER", "ORDINALITY", "ORGANIZATION", "OTHERS",
                    "OUT", "OUTER", "OUTFILE", "OVER", "OWNER", "P", "PACK_KEYS", "PAGE", "PARALLEL", "PARAMETERS",
                    "PARSER", "PARSE_TREE", "PARTIAL", "PARTITION", "PARTITIONING", "PARTITIONS", "PASSWORD", "PASSWORD_LOCK_TIME",
                    "PATH", "PERCENT_RANK", "PERSIST", "PERSIST_ONLY", "PHASE", "PLUGIN", "PLUGINS", "PLUGIN_DIR", "POINT",
                    "POLYGON", "PORT", "PRECEDES", "PRECEDING", "PRECISION", "PREPARE", "PRESERVE", "PREV", "PRIMARY",
                    "PRIVILEGES", "PRIVILEGE_CHECKS_USER", "PROCEDURE", "PROCESS", "PROCESSLIST", "PROFILE", "PROFILES", "PROXY",
                    "PURGE", "Q", "QUALIFY", "QUARTER", "QUERY", "QUICK", "R", "RANDOM", "RANGE", "RANK",
                    "READ", "READS", "READ_ONLY", "READ_WRITE", "REAL", "REBUILD", "RECOVER", "RECURSIVE", "REDO_BUFFER_SIZE",
                    "REDUNDANT", "REFERENCE", "REFERENCES", "REGEXP", "REGISTRATION", "RELAY", "RELAYLOG", "RELAY_LOG_FILE",
                    "RELAY_LOG_POS", "RELAY_THREAD", "RELEASE", "RELOAD", "REMOVE", "RENAME", "REORGANIZE", "REPAIR", "REPEAT",
                    "REPEATABLE", "REPLACE", "REPLICA", "REPLICAS", "REPLICATE_DO_DB", "REPLICATE_DO_TABLE", "REPLICATE_IGNORE_DB",
                    "REPLICATE_IGNORE_TABLE", "REPLICATE_REWRITE_DB", "REPLICATE_WILD_DO_TABLE", "REPLICATE_WILD_IGNORE_TABLE",
                    "REPLICATION", "REQUIRE", "REQUIRE_ROW_FORMAT", "RESET", "RESIGNAL", "RESOURCE", "RESPECT", "RESTART",
                    "RESTORE", "RESTRICT", "RESUME", "RETAIN", "RETURN", "RETURNED_SQLSTATE", "RETURNING", "RETURNS", "REUSE",
                    "REVERSE", "REVOKE", "RIGHT", "RLIKE", "ROLE", "ROLLBACK", "ROLLUP", "ROTATE", "ROUTINE", "ROW",
                    "ROWS", "ROW_COUNT", "ROW_FORMAT", "ROW_NUMBER", "RTREE", "S", "S3", "SAVEPOINT", "SCHEDULE",
                    "SCHEMA", "SCHEMAS", "SCHEMA_NAME", "SECOND", "SECONDARY", "SECONDARY_ENGINE", "SECONDARY_ENGINE_ATTRIBUTE",
                    "SECONDARY_LOAD", "SECONDARY_UNLOAD", "SECOND_MICROSECOND", "SECURITY", "SELECT", "SENSITIVE",
                    "SEPARATOR", "SERIAL", "SERIALIZABLE", "SERVER", "SESSION", "SET", "SHARE", "SHOW", "SHUTDOWN",
                    "SIGNAL", "SIGNED", "SIMPLE", "SKIP", "SLAVE", "SLOW", "SMALLINT", "SNAPSHOT", "SOCKET",
                    "SOME", "SONAME", "SOUNDS", "SOURCE", "SOURCE_AUTO_POSITION", "SOURCE_HOST", "SOURCE_MASTER", "SOURCE_PORT",
                    "SPATIAL", "SPECIFIC", "SQL", "SQL_AUTO_IS_NULL", "SQL_BIG_RESULT", "SQL_BUFFER_RESULT", "SQL_CACHE",
                    "SQL_CALC_FOUND_ROWS", "SQL_NO_CACHE", "SQL_SMALL_RESULT", "SQL_TSI_DAY", "SQL_TSI_FRAC_SECOND", "SQL_TSI_HOUR",
                    "SQL_TSI_MINUTE", "SQL_TSI_MONTH", "SQL_TSI_QUARTER", "SQL_TSI_SECOND", "SQL_TSI_WEEK", "SQL_TSI_YEAR",
                    "SSL", "START", "STARTING", "STARTUP", "STATEMENT", "STATS_AUTO_RECALC", "STATS_PERSISTENT",
                    "STATS_SAMPLE_PAGES", "STORAGE", "STORED", "STOP", "STORAGE_ENGINE", "STOP", "STRING", "SUBJECT",
                    "SUBPARTITION", "SUBPARTITIONS", "SUPER", "SUSPEND", "SWITCH", "SYNTAX", "SYSTEM", "TABLE",
                    "TABLES", "TABLESPACE", "TABLE_NAME", "TEMPORARY", "TERMINATED", "TEXT", "THAN", "THEN", "TIME",
                    "TIMEOUT", "TO", "TRAILING", "TRANSACTION", "TRANSACTIONS", "TRIGGER", "TRUE", "TRUNCATE",
                    "U", "UNCOMMITTED", "UNDEFINED", "UNION", "UNIQUE", "UNKNOWN", "UNLOCK", "UNSIGNED", "UPDATE",
                    "UPGRADE", "USER", "USAGE", "USE", "USING", "UTC_DATE", "UTC_TIME", "UTC_TIMESTAMP", "VALIDATION",
                    "VALUE", "VARIABLES", "VARIANCE", "VARYING", "VIEW", "VIEWS", "WAIT", "WHEN", "WHERE",
                    "WHILE", "WINDOW", "WITH", "WITH", "WITHOUT", "WORK", "WRITE", "YEAR", "YEAR_MONTH",
                    "ZONE"
            },
            // Postgre
            {
                // keywords
                    "ABORT", "ABS", "ABSENT", "ABSOLUTE", "ACCESS", "ACCORDING", "ACOS", "ACTION", "ADA",
                    "ADD", "ADMIN", "AFTER", "AGGREGATE", "ALL", "ALLOCATE", "ALSO", "ALTER", "ALWAYS",
                    "ANALYSE", "ANALYZE", "AND", "ANY", "ANY_VALUE", "ARE", "ARRAY", "ARRAY_AGG", "AS",
                    "ASC", "ASENSITIVE", "ASIN", "ASSERTION", "ASSIGNMENT", "ASYMMETRIC", "AT", "ATAN",
                    "ATOMIC", "ATTACH", "ATTRIBUTE", "ATTRIBUTES", "AUTHORIZATION", "AVG", "BEFORE", "BEGIN",
                    "BETWEEN", "BIGINT", "BINARY", "BIT", "BLOB", "BOOLEAN", "BOTH", "BY", "CALL", "CASCADE",
                    "CASE", "CAST", "CATALOG", "CHAR", "CHARACTER", "CHECK", "CLOB", "CLOSE", "COALESCE",
                    "COLLATE", "COLUMN", "COMMIT", "CONNECT", "CONSTRAINT", "CONTINUE", "CONVERT", "COPY",
                    "CREATE", "CROSS", "CURRENT", "CURSOR", "DATABASE", "DAY", "DEALLOCATE", "DEC", "DECIMAL",
                    "DECLARE", "DEFAULT", "DELETE", "DESC", "DESCRIBE", "DISCONNECT", "DISTINCT", "DO",
                    "DOMAIN", "DOUBLE", "DROP", "EACH", "ELSE", "ENCODING", "END", "ESCAPE", "EXCEPT",
                    "EXISTS", "EXTERNAL", "EXTRACT", "FALSE", "FETCH", "FIRST", "FLOAT", "FOREIGN", "FROM",
                    "FULL", "FUNCTION", "GRANT", "GROUP", "HAVING", "HOUR", "IDENTITY", "IF", "IMMEDIATE",
                    "IN", "INDEX", "INNER", "INSERT", "INT", "INTEGER", "INTERSECT", "INTERVAL", "INTO",
                    "IS", "JOIN", "KEY", "LANGUAGE", "LAST", "LEADING", "LEFT", "LIKE", "LIMIT", "LOCAL",
                    "MATCH", "MAX", "MIN", "MOD", "MONTH", "NATURAL", "NOT", "NULL", "NUMERIC", "ON",
                    "ONLY", "OPEN", "OR", "ORDER", "OUTER", "OVER", "PARTITION", "PERCENT", "PLACING",
                    "POSITION", "PRECISION", "PREPARE", "PRIMARY", "PROCEDURE", "PUBLIC", "REAL", "REFERENCES",
                    "RELEASE", "REVOKE", "RIGHT", "ROLLBACK", "ROW", "ROWS", "SAVEPOINT", "SCHEMA", "SELECT",
                    "SESSION", "SET", "SOME", "SYMMETRIC", "TABLE", "TEXT", "THEN", "TIME", "TIMESTAMP",
                    "TO", "TRAILING", "TRANSACTION", "TRUE", "UNION", "UNIQUE", "UPDATE", "USER", "USING",
                    "VALUES", "VARCHAR", "VIEW", "WHEN", "WHERE", "WITH", "YEAR", "ZONE",
                    // types
                    "BIGINT", "BINARY", "BIT", "BLOB", "BOOLEAN", "CHAR", "CHARACTER", "CLOB", "DATE",
                    "DEC", "DECIMAL", "DOUBLE", "FLOAT", "INTEGER", "INTERVAL", "JSON", "NUMERIC",
                    "REAL", "SMALLINT", "TEXT", "TIME", "TIMESTAMP", "UUID", "VARBINARY", "VARCHAR",
                    // Functions
                    "CEIL()", "CEILING()", "CHAR_LENGTH()", "CHARACTER_LENGTH()", "COALESCE()", "CORR()", "COS()", "COSH()",
                    "COUNT()", "COVAR_POP()", "COVAR_SAMP()", "DEGREES()", "DENSE_RANK()", "EXP()", "FLOOR()", "LAG()",
                    "LEAD()", "LN()", "LOG()", "LOG10()", "LOWER()", "MAX()", "MEDIAN()", "MIN()", "MODE()", "PERCENTILE_CONT()",
                    "PERCENTILE_DISC()", "PI()", "POSITION()", "POWER()", "RADIANS()", "RANK()", "ROUND()", "RPAD()", "RTRIM()",
                    "SIGN()", "SIN()", "SINH()", "SQRT()", "STDDEV_POP()", "STDDEV_SAMP()", "SUBSTRING()", "SUM()", "TAN()",
                    "TANH()", "TRANSLATE()", "TRIM()", "UPPER()", "VAR_POP()", "VAR_SAMP()", "WIDTH_BUCKET()"
            }};

    public static String[] getWords(final int index) {
        return words[index];
    }

}
